site/src/Librecores/ProjectRepoBundle/Entity/Project.php
<?php

namespace Librecores\ProjectRepoBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * A project
 *
 * A project is a sufficiently independent piece of software or hardware. It
 * can be associated with a user or with an organization.
 *
 * @ORM\Table("Project", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="projectname_full",
 *         columns={"name", "parentUser_id", "parentOrganization_id"})
 * })
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 *
 * @UniqueEntity(
 *     fields={"parentUser", "parentOrganization", "name"},
 *     errorPath="name",
 *     message="A project with that name already exists.",
 *     ignoreNull=false
 * )
 */
class Project
{
    const STATUS_ASSIGNED = 'ASSIGNED';
    const STATUS_UNASSIGNED = 'UNASSIGNED';
    /**
     * Classifications assigned to this project
     *
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="ProjectClassification", mappedBy="project",cascade={"persist", "remove"},
     *                orphanRemoval=true)
     * @ORM\JoinColumn(name="projectId", referencedColumnName="id")
     */
    protected $classifications;
    /**
     * Internal project ID
     *
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * Status of the project
     *
     * @var string
     *
     * @Assert\Choice(choices = {"ASSIGNED", "UNASSIGNED"})
     *
     * @ORM\Column(type="string", options={"default" : Project::STATUS_ASSIGNED})
     */
    private $status = self::STATUS_ASSIGNED;
    /**
     * User owning this project
     *
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="projects")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $parentUser;

    // Associations
    /**
     * Organization owning this project
     *
     * @var Organization
     *
     * @ORM\ManyToOne(targetEntity="Organization", inversedBy="projects")
     * @ORM\JoinColumn(nullable=true)
     */
    private $parentOrganization;
    /**
     * Short name of the project
     *
     * This field is used for the URL component (e.g.
     * http://librecores.org/parent/name). It's user-visible, but is limited
     * in the allowed characters and length. Think of it like a project's
     * username.
     *
     * @var string
     *
     * @Assert\Regex("/^[a-z][a-z0-9-]+$/")
     * @Assert\Length(min = 4, max = 30)
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * Display name of the project
     *
     * This is the "more human-readable" version of Project::$name. Think of it
     * like the real name of a user.
     *
     * @var string
     *
     * @Assert\NotBlank
     * @Assert\Length(min = 5, max = 100)
     *
     * @ORM\Column(name="displayName", type="string", length=100)
     */
    private $displayName;

    /**
     * The tagline of the project
     *
     * A tagline is a short and to the point description of what the project
     * does.
     *
     * @var string
     *
     * @Assert\Length(max = 140)
     *
     * @ORM\Column(name="tagline", type="string", length=140, nullable=true)
     */
    private $tagline;

    /**
     * Project web site URL
     *
     * @var string
     *
     * @Assert\Length(max = 255)
     * @Assert\Url
     *
     * @ORM\Column(name="projectUrl", type="string", length=255, nullable=true)
     */
    private $projectUrl;

    /**
     * URL to the issue/bug tracker
     *
     * @var string
     *
     * @Assert\Length(max = 255)
     * @Assert\Url
     *
     * @ORM\Column(name="issueTracker", type="string", length=255, nullable=true)
     */
    private $issueTracker;

    /**
     * @var SourceRepo
     *
     * @Assert\Type(type="Librecores\ProjectRepoBundle\Entity\SourceRepo")
     * @Assert\Valid()
     *
     * @ORM\OneToOne(targetEntity="SourceRepo", inversedBy="project", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="sourceRepo_id", referencedColumnName="id", nullable=true, onDelete="cascade")
     */
    private $sourceRepo;

    /**
     * Name of the license
     *
     * @var string
     *
     * @Assert\Length(max = 100)
     *
     * @ORM\Column(type="string", nullable=true, length=100)
     */
    private $licenseName;

    /**
     * Full license text in HTML
     *
     * @var string
     *
     * @Assert\Length(max = 64000)
     *
     * @ORM\Column(type="text", nullable=true, length=64000)
     */
    private $licenseText;

    /**
     * Update the license text automatically from the source code repository.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : true})
     */
    private $licenseTextAutoUpdate = true;

    /**
     * Project description in HTML
     *
     * @var string
     *
     * @Assert\Length(max = 64000)
     *
     * @ORM\Column(type="text", nullable=true, length=64000)
     */
    private $descriptionText;

    /**
     * Update the description text automatically from the source code repository
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : true})
     */
    private $descriptionTextAutoUpdate = true;

    /**
     * The project's data is currently being processed
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $inProcessing = false;

    /**
     * The date when this project was added to LibreCores
     *
     * @var DateTime date/time in UTC
     *
     * @see __construct()
     *
     * @ORM\Column(type="datetime")
     */
    private $dateAdded;

    /**
     * The date when the metadata of this project (i.e. the fields in this
     * entity) were last modified.
     *
     * This field is updated automatically when saving this entity.
     *
     * @see __construct()
     * @see updateDateLastModified()
     *
     * @var DateTime date/time in UTC
     *
     * @ORM\Column(type="datetime")
     */
    private $dateLastModified;

    /**
     * The date when the last activity occurred.
     *
     * Commits, discussions in issue trackers, releases, pull requests
     * are treated as activity.
     *
     * @var DateTime date/time in UTC
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateLastActivityOccurred;

    /**
     * Forks of this repository in the repository host
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $forks;

    /**
     * Forks of this repository in the repository host
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $openPullRequests;

    /**
     * Forks of this repository in the repository host
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $openIssues;

    /**
     * Stars of this repository in the repository host
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $stars;

    /**
     * Watchers of this repository in the repository host
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $watchers;

    /**
     * Releases of this project
     *
     * @var ProjectRelease[]
     *
     * @ORM\Column(type="array")
     */
    private $releases;

    /**
     * Code quality metrics for the project
     *
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $qualityScore;

    /**
     * Constructor
     */
    public function __construct()
    {
        // record the date/time of the project creation
        $this->setDateAdded(new DateTime());
        $this->setDateLastModified(new DateTime());
        $this->classifications = new ArrayCollection();
    }

    /**
     * Get child Classifications array
     *
     * This function returns all child Classifications of a project
     *
     * @return array
     */
    public function getClassificationArray()
    {
        $classifications = $this->getClassification();
        $classificationArray = [];
        foreach ($classifications as $classification) {
            $classificationArray[] = $classification->getClassification();
        }

        return $classificationArray;
    }

    /**
     * Get the classification hierarchy
     *
     * This functions returns the classification hierarchy levels
     *
     * @return array
     */
    public function getCategoryLists()
    {
        $classifications = $this->getClassificationArray();
        $categoryLevels = [];
        foreach ($classifications as $classification) {
            $categories = explode('::', $classification);
            $catIncrement = '';
            for ($i = 0; $i < count($categories); $i++) {
                if (isset($categories[$i])) {
                    $catIncrement = $i === 0 ? $categories[$i] : $catIncrement.'::'.$categories[$i];
                    $categoryLevels['lvl'.$i][] = $catIncrement;
                }
            }
        }

        return $categoryLevels;
    }

    /**
     * Update $dateLastModified
     *
     * This is called automatically by Doctrine.
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateDateLastModified()
    {
        $this->setDateLastModified(new DateTime());
    }

    /**
     * Get the name of the "parent" of this project
     *
     * A parent can either be a user or an organization. Use this for display
     * purposes only.
     *
     * @return string the parent name
     *
     * @see getParentOrganization()
     * @see getParentUser()
     */
    public function getParentName()
    {

site/src/Librecores/ProjectRepoBundle/Controller/DefaultController.php
<?php

namespace Librecores\ProjectRepoBundle\Controller;

use App\Entity\Organization;
use App\Entity\User;
use App\Repository\OrganizationRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends AbstractController
{
    /**
     * Render the project overview page
     *
     * @return Response
     */
    public function indexAction()
    {
        return $this->render('default/index.html.twig');
    }

    /**
     * Display a user or an organization
     *
     * @param string                 $userOrOrganization
     * @param OrganizationRepository $organizationRepository
     * @param UserRepository         $userRepository
     *
     * @return Response
     *
     * @throws NonUniqueResultException
     */
    public function userOrgViewAction(
        string $userOrOrganization,
        OrganizationRepository $organizationRepository,
        UserRepository $userRepository
    ) {
        $uoo = $this->getUserOrOrg(
            $userOrOrganization,
            $organizationRepository,
            $userRepository
        );

        if ($uoo instanceof User) {
            return $this->forward(
                'LibrecoresProjectRepoBundle:User:view',
                array('user' => $uoo)
            );
        }
        if ($uoo instanceof Organization) {
            return $this->forward(
                'LibrecoresProjectRepoBundle:Organization:view',
                array('organization' => $uoo)
            );
        }

        // and 404 if it's neither
        throw $this->createNotFoundException('User or organization not found.');
    }

    /**
     * Display the organization settings page
     *
     * @param string                 $userOrOrganization     name of the user
     *                                                       or organization
     * @param OrganizationRepository $organizationRepository autowired
     * @param UserRepository         $userRepository         autowired
     *
     * @return Response
     *
     * @throws NonUniqueResultException
     */
    public function userOrgSettingsAction(
        $userOrOrganization,
        OrganizationRepository $organizationRepository,
        UserRepository $userRepository
    ) {
        $uoo = $this->getUserOrOrg(
            $userOrOrganization,
            $organizationRepository,
            $userRepository
        );

        if ($uoo instanceof User) {
            if ($uoo->getId() !== $this->getUser()->getId()) {
                throw $this->createAccessDeniedException();
            }

            return $this->forward(
                'LibrecoresProjectRepoBundle:User:profileSettings',
                array('user' => $userOrOrganization)
            );
        }

        if ($uoo instanceof Organization) {
            return $this->forward(
                'LibrecoresProjectRepoBundle:Organization:settings',
                array('organization' => $uoo)
            );
        }

        // and 404 if it's neither
        throw $this->createNotFoundException('User or organization not found.');
    }

    /**
     * Search for a project
     *
     * @param Request $req
     *
     * @return Response
     */
    public function searchAction(Request $req)
    {
        $searchType = $req->get('type');
        $searchQuery = $req->get('query');

        $searchType = ($searchType === null ? 'projects' : $searchType);

        return $this->render(
            'default/project_search.html.twig',
            [
                'searchType' => $searchType,
                'searchQuery' => $searchQuery,
            ]
        );
    }


    public function removeTrailingSlashAction(Request $request)
    {
        $pathInfo = $request->getPathInfo();
        $requestUri = $request->getRequestUri();

        $url = str_replace($pathInfo, rtrim($pathInfo, ' /'), $requestUri);

        return $this->redirect($url, 301);
    }

    /**
     * Get an user or organization entity with the given name
     *
     * @param string                 $userOrOrganization
     * @param OrganizationRepository $organizationRepository
     * @param UserRepository         $userRepository
     *
     * @return User|Organization|null user or organization entity, or null if
     *   no entity with the given name exists.
     * @throws NonUniqueResultException
     */
    private function getUserOrOrg(
        $userOrOrganization,
        OrganizationRepository $organizationRepository,
        UserRepository $userRepository
    ) {
        // try user first
        $user = $userRepository->findOneByUsername($userOrOrganization);

        if ($user !== null) {
            return $user;
        }

        // then organization
        $org = $organizationRepository->findOneByName($userOrOrganization);

        return $org;
    }
}

site/src/Librecores/ProjectRepoBundle/Resources/views/Default/delete.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Delete project - LibreCores{% endblock %}

{% block content %}
<h1>Project Deleted</h1>

<p>Your project {{ Fqname }} has been deleted from LibreCores.<br><br>

  Do you want to add a new project? Or search for an existing one?
</p>
{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/Default/project_new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
Add your project to LibreCores
{% endblock %}

{% block pagepath %}Home &raquo; Add Project to LibreCores{% endblock %}

{% block content %}
<h1>Add your project to LibreCores</h1>

<p>Adding your project to LibreCores is easy: just give us the name of your
project and the location of the source code, and we'll take care of
the rest.</p>

{{ form_start(form) }}
  <div class="form-group">
    {{ form_label(form.name, "What's the name of your project?") }}

    {{ form_errors(form.parentName) }}
    {{ form_errors(form.name) }}

    <div class="form-inline">
      {{ form_label(form.parentName, null, {'label_attr': {'class': 'sr-only'}}) }}
      {{ form_widget(form.parentName) }} /
      {{ form_widget(form.name, {'attr': {'placeholder': 'project name'}}) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.sourceRepo.url, "Where can we find the source code of your project?") }}
    {{ form_errors(form.sourceRepo) }}

    <div class="form-inline">
      {{ form_label(form.sourceRepo.type, null, {'label_attr': {'class': 'sr-only'}}) }}
      {{ form_widget(form.sourceRepo.type) }}
      {{ form_widget(form.sourceRepo.url, {'attr': {'style': 'width:500px', 'placeholder': 'URL, e.g. https://github.com/yourname/project'}}) }}
    </div>
  </div>

  {{ form_row(form.save) }}
{{ form_end(form) }}

{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/Default/project_settings.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
{{ project.getFullName() }} @ LibreCores: Settings
{% endblock %}

{% block pagepath %}Home &raquo; Projects &raquo; {{ project.getFullName() }} &raquo; Settings{% endblock %}

{% block content %}
<h1 class="projectname"><a href="{{ path('librecores_project_repo_project_view', {'parentName':
  project.getParentName(), 'projectName': project.getName()}) }}">{{ project.getFullName() }}</a>: Settings</h1>

<div class="row">
<div class="col-md-2">
  <ul class="list-group">
    <a class="list-group-item" href="{{ path('librecores_project_repo_project_view', {'parentName':
  project.getParentName(), 'projectName': project.getName()}) }}">
      <i class="fa fa-bookmark fa-fw"></i>
      Project
    </a>
    <a class="list-group-item active" href="#">
      <i class="fa fa-cogs fa-fw"></i>Settings
    </a>
  </ul>
</div>
<div class="col-md-10">

{{ form_start(form) }}
  {{ form_errors(form) }}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Tagline</h3>
    </div>
    <div class="panel-body">
      <p><i>A short and to-the-point (140 characters or less) description what this project is all about.</i></p>

      {{  form_row(form.tagline, {'label': false}) }}
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Description</h3>
    </div>
    <div class="panel-body">
      {{  form_row(form.descriptionTextAutoUpdate, {'label': false}) }}
      <div id="descriptionText_div"
           style="padding-left: 15px; display: {% if form.vars.value.descriptionTextAutoUpdate %}none{% else %}block{% endif %};">
        {{ form_row(form.descriptionText, {'attr': {'data-provide': 'markdown'}}) }}
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Resources</h3>
    </div>
    <div class="panel-body">
      {{ form_row(form.projectUrl) }}
      {{ form_row(form.issueTracker) }}
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Source Code Repository</h3>
    </div>
    <div class="panel-body">
      {{ form_row(form.sourceRepo, {'label': false}) }}
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">License</h3>
    </div>
    <div class="panel-body">
      {{ form_row(form.licenseName) }}

      {{ form_row(form.licenseTextAutoUpdate) }}
      <div id="licenseText_div" style="padding-left: 15px; display: {% if  form.vars.value.licenseTextAutoUpdate %}none{% else %}block{% endif %};">
        {{ form_row(form.licenseText, {'attr': {'data-provide': 'markdown'}}) }}
      </div>
    </div>
  </div>
{{ form_end(form) }}
{% endblock %}

{% block pagejs %}
$(document).ready(function(){
  /* toggle text boxes in respect to the auto update settings */
  $('#{{ form.descriptionTextAutoUpdate.vars.id }}').on('change', function() {
    var au = $('input[name="{{ form.descriptionTextAutoUpdate.vars.full_name }}"]:checked').val() == '1';
    var el = $('#descriptionText_div');
    au ? el.hide() : el.show();
  });
  $('#{{ form.licenseTextAutoUpdate.vars.id }}').on('change', function() {
    var au = $('input[name="{{ form.licenseTextAutoUpdate.vars.full_name }}"]:checked').val() == '1';
    var el = $('#licenseText_div');
    au ? el.hide() : el.show();
  });
});
{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/Default/project_view.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
{{ project.getFullName() }} @ LibreCores
{% endblock %}

{% block pagepath %}Home &raquo; Projects &raquo; {{ project.getFullName() }}{% endblock %}

{% block content %}
<h1 style="margin-bottom:5px">{{ project.getFullName() }}</h1>
{% if project.isAssigned() %}
  {% if project.getParentOrganization() != null %}
    <p>by {{ project.getParentOrganization().getName() }}
  {% else %}
    <p>by {{ project.getParentUser().getUsername() }}
  {% endif %}
{% else %}
  <p><i>This project is currently not claimed by anyone. <a href="#">Is it yours?</a></i></p>
{% endif %}

<div class="row">
<div class="col-md-8">


{% if project.getTagline() %}
<p style="margin-top:20px; margin-bottom:20px;">
  {{ project.getTagline() }}
</p>
{% endif %}


<ul class="nav nav-tabs">
  <li role="presentation" class="active">
    <a href="#README" aria-controls="settings" role="tab" data-toggle="tab">
      <i class="fa fa-book" aria-hidden="true"></i>
      README
    </a>
  </li>
  <li role="presentation">
    <a href="#LICENSE" aria-controls="settings" role="tab" data-toggle="tab">
      <i class="fa fa-copyright" aria-hidden="true"></i>
      LICENSE
    </a>
  </li>
  {% if is_granted("edit", project) %}
  <li>
    <a href="{{ path('librecores_project_repo_project_settings', {'parentName':
  project.getParentName(), 'projectName': project.getName()}) }}" aria-controls="settings" role="tab">
      <i class="fa fa-cogs fa-fw" aria-hidden="true"></i>
      Settings
    </a>
  </li>
  {% endif %}
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="README">
  {{  project.getDescriptionText()|markdown }}
  </div>
  <div role="tabpanel" class="tab-pane" id="LICENSE">
  {{  project.getLicenseText()|markdown }}
  </div>
</div>

</div>
<div class="col-md-4">
  <div class="librecores-project-infobox" style="background-color: #f7f7f7; padding: 10px; border-radius: 3px;">
    <p><b>Data Sheet</b></p>
    <p>
      {% if project.getProjectUrl() %}
      <i class="fa fa-home" aria-hidden="true"></i>
      <a href="{{ project.getProjectUrl()|escape('html_attr') }}">Project Web Site</a>
      <br/>
      {% endif %}

      {% if project.getSourceRepo().getUrl() %}
      {% if project.getSourceRepo.getType() == 'git'  %}
        <i class="fa fa-git-square" aria-hidden="true"></i>
      {% else %}
        {{ project.getSourceRepo.getType() }}:
      {% endif %}
      {{ project.getSourceRepo().getUrl() }}
      <br/>
      {% endif %}

      {% if project.getLicenseName() %}
      <i class="fa fa-copyright" aria-hidden="true"></i>
      {{ project.getLicenseName() }}
      <br/>
      {% endif %}

      {% if project.getIssueTracker() %}
      <i class="fa fa-bug" aria-hidden="true"></i>
      <a href="{{ project.getIssueTracker()|escape('html_attr') }}">Issue Tracker</a>
      <br/>
      {% endif %}
    </p>
  </div>

  {# XXX: Tags are not yet supported
  <div class="librecores-project-infobox" style="background-color: #f7f7f7; padding: 10px; border-radius: 3px;">
    <p><b>Tags</b></p>
    <p>CPU, some, tag, what, else</p>
  </div>
  #}
</div>

</div>
{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/Default/project_wait_processing.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
{{ project.getFullName() }} @ LibreCores
{% endblock %}

{% block pagepath %}Home &raquo; Projects &raquo; {{ project.getFullName() }}{% endblock %}

{% block content %}
<h1>Just a moment, we're currently processing this project!</h1>

You'll be redirected to the project page shortly
(or you can <a href="{{ app.request.uri }}">refresh</a> the page yourself).

{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/Default/user_view.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
{{ user.getUsername() }} {% if user.getName() %}({{ user.getName() }}){% endif %}@ LibreCores
{% endblock %}

{% block pagepath %}Home &raquo; Projects &raquo; {{ user.getUsername() }}{% endblock %}

{% block content %}
<h1 class="projectname">{{ user.getUsername() }}</h1>

{{ user.getUsername() }} joined LibreCores
<time datetime="{{ user.getCreatedAt()|date("c", "UTC") }}"
      data-livestamp="{{ user.getCreatedAt()|date("c", "UTC") }}">
  on {{ user.getCreatedAt()|date("d F Y H:i", "UTC") }} UTC
</time>.

<h2>Projects</h2>
{% for project in user.getProjects() %}
  <h3>{{ project.getName() }}</h3>
  {{ project.getTagline() }}
{% else %}
  {{ user.getUsername() }} has not yet created a project.
{% endfor %}
{% endblock %}