site/src/Librecores/ProjectRepoBundle/Entity/SourceStats.php
<?php

namespace Librecores\ProjectRepoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;

/**
 * Statistics about the source code of a repository
 *
 * @author Amitosh Swain Mahapatra <amitosh.swain@gmail.com>
 *
 * @ORM\Embeddable()
 */
class SourceStats
{
    /**
     * Development by a small team with intermediate experience
     * working on a project with less stringent requirements. Usually for small
     * software projects.
     */
    const DEVELOPMENT_TYPE_ORGANIC = 1;

    /**
     * Development by a sizable number of developers with mixed
     * experience on various parts of the system. Requirements may be range from
     * well-defined to rigid.
     */
    const DEVELOPMENT_TYPE_SEMI_DETACHED = 2;

    /**
     * Development on projects with stringent requirements such as
     * embedded projects.
     */
    const DEVELOPMENT_TYPE_EMBEDDED = 3;

    /**
     * Is source stats available
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $available = false;

    /**
     * Total files in repository
     *
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $totalFiles = 0;

    /**
     * Total lines of code in the repository
     *
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $totalLinesOfCode = 0;

    /**
     * Total comment lines in the repository
     *
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $totalLinesOfComments = 0;

    /**
     * Total blank lines in the repository
     *
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $totalBlankLines = 0;

    /**
     * Stats about all other languages used by this repository
     *
     * @var LanguageStat[]
     *
     * @ORM\Column(type="array")
     */
    private $languageStats;

    /**
     * SourceStats constructor.
     */
    public function __construct()
    {
        $this->languageStats = [];
    }

    /**
     * @return bool
     */
    public function isAvailable(): bool
    {
        return $this->available;
    }

    /**
     * @param bool $available
     *
     * @return SourceStats
     */
    public function setAvailable(bool $available)
    {
        $this->available = $available;

        return $this;
    }

    /**
     * @return int
     */
    public function getTotalFiles(): int
    {
        return $this->totalFiles;
    }

    /**
     * @param int $totalFiles
     *
     * @return SourceStats
     */
    public function setTotalFiles(int $totalFiles)
    {
        $this->totalFiles = $totalFiles;

        return $this;
    }

    /**
     * @return int
     */
    public function getTotalLinesOfCode(): int
    {
        return $this->totalLinesOfCode;
    }

    /**
     * @param int $totalLinesOfCode
     *
     * @return SourceStats
     */
    public function setTotalLinesOfCode(int $totalLinesOfCode)
    {
        $this->totalLinesOfCode = $totalLinesOfCode;

        return $this;
    }

    /**
     * @return int
     */
    public function getTotalLinesOfComments(): int
    {
        return $this->totalLinesOfComments;
    }

    /**
     * @param int $totalLinesOfComments
     *
     * @return SourceStats
     */
    public function setTotalLinesOfComments(int $totalLinesOfComments)
    {
        $this->totalLinesOfComments = $totalLinesOfComments;

        return $this;
    }

    /**
     * @return int
     */
    public function getTotalBlankLines(): int
    {
        return $this->totalBlankLines;
    }

    /**
     * @param int $totalBlankLines
     *
     * @return SourceStats
     */
    public function setTotalBlankLines(int $totalBlankLines)
    {
        $this->totalBlankLines = $totalBlankLines;

        return $this;
    }

    /**
     * @param LanguageStat $language
     *
     * @return SourceStats
     */
    public function addLanguageStat(LanguageStat $language)
    {
        $this->languageStats[] = $language;

        return $this;
    }

    /**
     * @param LanguageStat $language
     *
     * @return bool
     */
    public function removeLanguageStat(LanguageStat $language)
    {
        if (($key = array_search($language, $this->languageStats)) !== false) {
            unset($this->languageStats[$key]);

            return true;
        }

        return false;
    }

    /**
     * @return LanguageStat[]
     */
    public function getLanguageStats(): array
    {
        return $this->languageStats;
    }

    /**
     * Set languageStats
     *
     * @param LanguageStat[] $languageStats
     *
     * @return SourceStats
     */
    public function setLanguageStats($languageStats)
    {
        $this->languageStats = $languageStats;

        return $this;
    }

    /**
     * Get the total number of lines in the codebase
     *
     * @return int
     */
    public function getTotalLines(): int
    {
        return $this->totalLinesOfCode + $this->totalBlankLines + $this->totalLinesOfComments;
    }

    /**
     * Get comment to code ratio
     *
     * @return float
     */
    public function getCommentToCodeRatio(): float
    {
        if (0 === $this->totalLinesOfComments) {
            $ratio = 0;
        } else {
            $ratio = $this->totalLinesOfCode / $this->totalLinesOfComments;
        }

        return $ratio;
    }

    /**
     * Get the most used language in this repository
     *
     * @return string|null the primary language of this repository or false if
     *                      such information does not exist
     */
    public function getMostUsedLanguage(): ?string
    {
        $language = null;

        // only sort if language entries are present
        if (0 !== count($this->languageStats)) {
            $langStats = $this->languageStats;

            usort(
                $langStats,
                function (LanguageStat $a, LanguageStat $b) {
                    // we compare using file count, not loc
                    $aCount = $a->getFileCount();
                    $bCount = $b->getFileCount();

                    if ($aCount === $bCount) {
                        return 0;
                    }

                    return ($aCount > $bCount) ? -1 : 1;
                }
            );

            $language = $langStats[0]->getLanguage();
        }

        return $language;
    }

    // Estimation of project effort in man-months and development time in

    // months according to Constructive Cost Model (COCOMO)
    // https://en.wikipedia.org/wiki/COCOMO
    // Basic COCOMO is used to calculate the effort and development values.

    // References:

    // Roger S. Pressman, 1997. Software Engineering - A Practitioner's Approach, Fourth Edition.

    /**
     * Get estimated effort in man-months
     *
     * @param int $type Development type of the repository
     *
     * @return float effort in man-months
     */
    public function getCocomoEffort(int $type = self::DEVELOPMENT_TYPE_EMBEDDED): float
    {
        $kLoc = $this->totalLinesOfCode / 1000;

        switch ($type) {
            case self::DEVELOPMENT_TYPE_ORGANIC:
                $a = 2.4;
                $b = 1.05;
                break;
            case self::DEVELOPMENT_TYPE_SEMI_DETACHED:
                $a = 3.0;
                $b = 1.12;
                break;
            case self::DEVELOPMENT_TYPE_EMBEDDED:
                $a = 3.6;
                $b = 1.2;
                break;
            default:
                throw new InvalidArgumentException('Invalid development type');
        }

        return $a * pow($kLoc, $b);
    }


    /**
     * Get estimated duration in man-months
     *
     * @param int $type Development type of the repository
     *
     * @return float effort in man-months
     */
    public function getCocomoDuration(int $type = self::DEVELOPMENT_TYPE_EMBEDDED): float
    {
        $kLoc = $this->totalLinesOfCode / 1000;

        switch ($type) {
            case self::DEVELOPMENT_TYPE_ORGANIC:
                $d = 0.35;
                break;
            case self::DEVELOPMENT_TYPE_SEMI_DETACHED:
                $d = 0.38;
                break;
            case self::DEVELOPMENT_TYPE_EMBEDDED:
                $d = 0.32;
                break;
            default:
                throw new InvalidArgumentException('Invalid development type');
        }

        return 2.5 * pow($kLoc, $d);
    }

    /**
     * Get estimated number of developers
     *
     * @param int $type Development type of the repository
     *
     * @return int estimated number of developers
     */
    public function getCocomoTeamSize(int $type = self::DEVELOPMENT_TYPE_EMBEDDED): int
    {
        return ceil($this->getCocomoEffort($type) / $this->getCocomoDuration($type));
    }

    // TODO: Cost estimation by man-hours * median monthly wages of developers
}

site/src/Librecores/ProjectRepoBundle/Controller/UserController.php
<?php

namespace Librecores\ProjectRepoBundle\Controller;

use App\Entity\User;
use App\Form\Model\ResendConfirmationEmailRequest;
use App\Form\Type\ResendConfirmationEmailRequestType;
use App\Form\Type\UserProfileType;
use App\Security\Core\User\LibreCoresUserProvider;
use FOS\UserBundle\Form\Type\ChangePasswordFormType;
use FOS\UserBundle\Mailer\MailerInterface;
use FOS\UserBundle\Model\UserInterface;
use FOS\UserBundle\Model\UserManagerInterface;
use FOS\UserBundle\Util\TokenGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class UserController extends AbstractController
{

    /**
     * View a user's public profile
     *
     * @param Request $request
     * @param User    $user
     *
     * @return Response
     */
    public function viewAction(Request $request, User $user)
    {
        return $this->render(
            'user/view.html.twig',
            array('user' => $user)
        );
    }

    /**
     * User profile settings
     *
     * @param Request $request
     *
     * @return Response
     */
    public function profileSettingsAction(Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();

        $form = $this->createForm(UserProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }

        return $this->render(
            'user/settings_profile.html.twig',
            array('user' => $user, 'form' => $form->createView())
        );
    }

    /**
     * User connected services settings (such as GitHub or BitBucket)
     *
     * @param Request $request
     *
     * @return Response
     */
    public function connectionsSettingsAction(Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();

        return $this->render(
            'user/settings_connections.html.twig',
            array('user' => $user)
        );
    }

    /**
     * Successfully connected to an OAuth service
     *
     * As the HWIOAuthBundle doesn't support a nicer way for customization,
     * this action is forwarded from
     * HWI\Bundle\OAuthBundle\Controller\ConnectController:connectServiceAction()
     * through the overwritten template in
     * app/Resources/HWIOAuthBundle/views/Connect/connect_success.html.twig
     *
     * @param Request $request
     * @param string  $serviceName
     *
     * @return Response
     */
    public function connectionSuccessAction(Request $request, $serviceName)
    {
        $this->addFlash(
            'success',
            "You successfully connected your LibreCores account to "
            .ucfirst($serviceName)."."
        );

        return $this->redirectToRoute('librecores.user.settings.connections');
    }

    /**
     * Disconnect the user account from an OAuth service
     *
     * @param Request                $request
     * @param string                 $serviceName
     * @param LibreCoresUserProvider $accountConnector
     *
     * @return Response
     */
    public function disconnectFromOAuthServiceAction(
        Request $request,
        $serviceName,
        LibreCoresUserProvider $accountConnector
    ) {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $accountConnector->disconnect($this->getUser(), $serviceName);

        $this->addFlash(
            'success',
            "You successfully disconnected your LibreCores account from "
            .ucfirst($serviceName)."."
        );

        return $this->connectionsSettingsAction($request);
    }

    /**
     * Change user password
     *
     * @param Request              $request
     * @param UserManagerInterface $userManager
     *
     * @return Response
     */
    public function passwordSettingsAction(
        Request $request,
        UserManagerInterface $userManager
    ) {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }

        $validationGroups = ['ChangePassword', 'Default'];
        $form = $this->createForm(
            ChangePasswordFormType::class,
            $user,
            ['validation_groups' => $validationGroups]
        );
        $form->add('save', SubmitType::class, array('label' => 'Change password'));
        $form->setData($user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userManager->updateUser($user);

            $this->addFlash(
                'success',
                "Your password was successfully changed."
            );

            $url = $this->generateUrl('fos_user_profile_show');
            $response = new RedirectResponse($url);

            return $response;
        }

        return $this->render(
            'user/settings_password.html.twig',
            array('user' => $user, 'form' => $form->createView())
        );
    }

    /**
     * @param Request $request
     *
     * @return RedirectResponse|Response
     */
    public function resendConfirmationEmailAction(
        Request $request,
        MailerInterface $userMailer,
        TokenGeneratorInterface $tokenGenerator
    ) {

        $resendEmailRequest = new ResendConfirmationEmailRequest();
        $form = $this->createForm(ResendConfirmationEmailRequestType::class, $resendEmailRequest);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $resendEmailRequest->getUser();

            if (!$user->isEnabled()) {
                if (null === $user->getConfirmationToken()) {
                    $user->setConfirmationToken($tokenGenerator->generateToken());
                }

                $userMailer->sendConfirmationEmailMessage($resendEmailRequest->getUser());

                $request->getSession()->set('fos_user_send_confirmation_email/email', $user->getEmail());

                return $this->redirectToRoute('fos_user_registration_check_email');
            } else {
                $this->addFlash('warning', 'Account is already confirmed');
            }
        }

        return $this->render('user/resend_confirmation_email.html.twig', [ 'form' => $form->createView() ]);
    }
}

site/src/Librecores/ProjectRepoBundle/Resources/views/User/dashboard.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
  {{ user.getName() ? user.getName() : user.getUsername() }} @ LibreCores
{% endblock %}

{% block content %}
  <div class="librecores-user-page-header">
    {% if user.getName() %}
      <h1>{{ user.getName() }} <small>{{ user.getUsername() }}</small></h1>
    {% else %}
      <h1>{{ user.getUsername() }}</h1>
    {% endif %}
  </div>

  {{ user.getUsername() }} joined LibreCores
  <time datetime="{{ user.getCreatedAt()|date("c", "UTC") }}"
        data-livestamp="{{ user.getCreatedAt()|date("c", "UTC") }}">
    on {{ user.getCreatedAt()|date("d F Y H:i", "UTC") }} UTC
  </time><div class=""></div>
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-7">
      <h3>Projects</h3>
    </div>
    <div class="col-sm-3">
      <h3>Organizations</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <ul class="list-group">
        <li class="list-group-item">
          <a href="{{ path('librecores_project_repo_project_new') }}">
            New Project
          </a>
        </li>
        <li class="list-group-item">
          <a href="{{ path('librecores_project_repo_organization_new') }}">
            New Organization
          </a>
        </li>
        <li class="list-group-item">
          <a href="{{ path('librecores.user.settings.profile') }}" aria-controls="settings" role="tab">
            Profile
          </a>
        </li>
        <li class="list-group-item">
          <a href="{{ path('librecores_project_repo_organization_list') }}">
            Your Organizations
          </a>
        </li>
      </ul>
    </div>
    <div class="col-sm-7">
      {% for project in user.getProjects() %}
        <h2><a href="{{ path('librecores_project_repo_project_view', {'parentName':
            project.getParentName(), 'projectName': project.getName()}) }}">{{ project.getName() }}</a></h2>
        <div><i>
            added on {{ project.getDateAdded()|date('Y-m-d') }}
          </i></div>
        <div class="librecores-project-list-metadata">
          {% if project.sourceRepo.sourceStats.available %}
            <span class="metric metric-lang">
            <i class="fa fa-code"></i>
            <span class="sr-only">Major language: </span>
              {{ project.sourceRepo.sourceStats.mostUsedLanguage }}
          </span>
          {%  endif %}
          {% if project.dateLastActivityOccurred %}
            <span class="updated">
          <i class="fa fa-history"></i> Updated {{ project.dateLastActivityOccurred | time_diff }}
          </span>
          {% endif %}
        </div>
        <hr/>
      {% else %}
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") and (user.getUsername() == app.user.username) %}
          <p>You have not yet created a project.</p>
          <p><a href="{{ path('librecores_project_repo_project_new') }}">
              Add project
            </a></p>
        {% else %}
          {{ user.getUsername() }} has not yet created a project.
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-sm-3">
      {% for membership in user.getOrganizationMemberships() %}
        <a href="{{ path('librecores_project_repo_user_org_view', {'userOrOrganization':
          membership.getOrganization.getName()}) }}">{{ membership.getOrganization.getDisplayName() }}</a>
        {% if membership.getPermission == 'MEMBER' %} (Member) {% endif %}
        {% if membership.getPermission == 'ADMIN' %} (Admin) {% endif %}
        {% if user == app.user %}
          {% if membership.getPermission == 'REQUEST' %} (Join request in progress) {% endif %}
          {% if membership.getPermission == 'DENY' %} (Denied your request to join) {% endif %}
        {% endif %}
        {% if membership.getOrganization.getDescription() is not null %}
          - {{ membership.getOrganization.getDescription() }}{% endif %}<br/>
        <hr/>
      {% else %}
        {{ user.getUsername() }} has not yet joined an organization.
      {% endfor %}
    </div>
  </div>
{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/User/settings_base.html.twig
{#
Base template for all user settings pages
page path: n/a
#}
{% extends 'layout.html.twig' %}

{% block title %}
Settings for {{ user.getName() ? user.getName() : user.getUsername() }} @ LibreCores
{% endblock %}

{% block content %}
<div class="librecores-user-page-header">
{% if user.getName() %}
<h1>{{ user.getName() }} <small>{{ user.getUsername() }}</small></h1>
{% else %}
<h1>{{ user.getUsername() }}</h1>
{% endif %}
</div>

<ul class="nav nav-tabs librecores-tabs-topnav">
  <li role="presentation" class="active">
    <a href="{{ path('librecores.user.settings.profile') }}" aria-controls="settings" role="tab">
      <i class="fa fa-cogs fa-fw" aria-hidden="true"></i>
      Settings
    </a>
  </li>
</ul>

<div class="row">
<div class="col-sm-2">
  <ul class="list-group">
    <li class="list-group-item librecores-list-group-header">Personal Settings</li>

    <li class="list-group-item {{ settings_subpage == "profile" ? "active"}}">
      <a href="{{ path('librecores.user.settings.profile') }}">
        Profile Settings
      </a>
    </li>
    <li class="list-group-item {{ settings_subpage == "connections" ? "active"}}">
      <a href="{{ path('librecores.user.settings.connections') }}">
        Connected Services
      </a>
    </li>
    <li class="list-group-item {{ settings_subpage == "password" ? "active"}}">
      <a href="{{ path('librecores.user.settings.password') }}">
        Change Password
      </a>
    </li>
  </ul>
</div>
<div class="col-sm-10">
  {% block settings_content %}{% endblock %}
</div>
</div>

{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/User/settings_connections.html.twig
{#
Template for the user connected services settings page
page path: /user/settings/connected-services
#}
{% extends 'LibrecoresProjectRepoBundle:User:settings_base.html.twig' %}

{# Inform settings_base.html.twig about the page currently displayed #}
{% set settings_subpage = 'connections' %}

{% block settings_content %}

<p>You can connect your LibreCores account to an external account. This allows you
to login through the external account, and access the data stored there easily.
For example, you can import projects from GitHub more easily if you connect
your LibreCores account with your GitHub account.</p>


{% for serviceName in hwi_oauth_resource_owners() %}
  {% if user.isConnectedToOAuthService(serviceName) %}
    <p>
    Your account is connected to {{ serviceName|capitalize }}.
    (<a href="{{ path('librecores.user.settings.oauth-disconnect', { serviceName: serviceName }) }}">Disconnect</a>)
    </p>
  {% else %}
    <p>
      <a class="btn btn-social btn-{{ serviceName }}" href="{{ hwi_oauth_login_url(serviceName) }}">
        <i class="fa fa-{{ serviceName }}"></i> Connect to {{ serviceName|capitalize }}
      </a>
    </p>
  {% endif %}
{% endfor %}

{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/User/settings_password.html.twig
{#
Template for the user password settings page
page path: /user/settings/password
#}
{% extends 'LibrecoresProjectRepoBundle:User:settings_base.html.twig' %}

{# Inform settings_base.html.twig about the page currently displayed #}
{% set settings_subpage = 'password' %}


{% block settings_content %}
  {{ form_start(form) }}
  {{ form_widget(form) }}
  {{ form_end(form) }}
{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/User/settings_profile.html.twig
{#
Template for the user profile settings page
page path: /user/settings/profile
#}
{% extends 'LibrecoresProjectRepoBundle:User:settings_base.html.twig' %}

{# Inform settings_base.html.twig about the page currently displayed #}
{% set settings_subpage = 'profile' %}

{% block settings_content %}
  {{ form_start(form) }}
  {{ form_widget(form) }}
  {{ form_end(form) }}
{% endblock %}

site/src/Librecores/ProjectRepoBundle/Resources/views/User/view.html.twig
{#
Public profile of a user
page path: /USERNAME
#}
{% extends 'layout.html.twig' %}

{% block title %}
{{ user.getName() ? user.getName() : user.getUsername() }} @ LibreCores
{% endblock %}

{% block content %}
<div class="librecores-user-page-header">
{% if user.getName() %}
<h1>{{ user.getName() }} <small>{{ user.getUsername() }}</small></h1>
{% else %}
<h1>{{ user.getUsername() }}</h1>
{% endif %}
</div>

{{ user.getUsername() }} joined LibreCores
<time datetime="{{ user.getCreatedAt()|date("c", "UTC") }}"
      data-livestamp="{{ user.getCreatedAt()|date("c", "UTC") }}">
  on {{ user.getCreatedAt()|date("d F Y H:i", "UTC") }} UTC
</time>.

<h2>Projects</h2>
{% for project in user.getProjects() %}
  <a href="{{ path('librecores_project_repo_project_view', {'parentName':
          project.getParentName(), 'projectName': project.getName()}) }}">{{ project.getName() }}</a>
  {% if project.getTagline() is not null %} - {{ project.getTagline() }}{% endif %}<br/>
{% else %}
  {% if is_granted("IS_AUTHENTICATED_REMEMBERED") and (user.getUsername() == app.user.username) %}
  <p>You have not yet created a project.</p>
  <p><a href="{{ path('librecores_project_repo_project_new') }}">
    Add project
  </a></p>
  {% else %}
  {{ user.getUsername() }} has not yet created a project.
  {% endif %}

{% endfor %}

<h2>Organizations</h2>
{% for membership in user.getOrganizationMemberships() %}
    <a href="{{ path('librecores_project_repo_user_org_view', {'userOrOrganization':
        membership.getOrganization.getName()}) }}">{{ membership.getOrganization.getDisplayName() }}</a>
  {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
    {% if membership.getPermission == 'MEMBER' %} (Member) {% endif %}
    {% if membership.getPermission == 'ADMIN' %} (Admin) {% endif %}
    {% if user == app.user %}
        {% if membership.getPermission == 'REQUEST' %} (Join request in progress) {% endif %}
        {% if membership.getPermission == 'DENY' %} (Denied your request to join) {% endif %}
    {% endif %}
  {% endif %}
    {% if membership.getOrganization.getDescription() is not null %}
     - {{ membership.getOrganization.getDescription() }}{% endif %}<br/>
{% else %}
    {{ user.getUsername() }} has not yet joined an organization.
{% endfor %}
{% endblock %}